[package]
name = "bevy_dolly"
version = "0.0.1"
authors = ["Black Phlox <bphlox@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
readme = "README.md"
repository = "https://github.com/BlackPhlox/bevy_dolly"
documentation = "https://docs.rs/bevy_dolly"
description = "TBA"
keywords = ["gamedev", "bevy", "camera", "fps", "3d", ]
categories = ["game-development", "game-engines", ]
exclude = [
    "assets/*",
    ".github/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "bevy_dolly"

[dependencies]
bevy = { version = "0.5", default-features = false, features = ["render"]}

[dev-dependencies]
bevy = { version = "0.5" }

[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main" }
